name: Build and Push Docker Image

on:
  push:
    branches:
      - github-action

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build the Docker image
        run: docker build --platform=linux/amd64 -t 20522153/myporfolio:latest .

      - name: Log in to Docker Hub
        run: docker login -u 20522153 -p ${{ vars.HUB_DOCKER_COM_PASSWORD}}

      - name: Push Docker image to Docker Hub
        run: docker push 20522153/myporfolio:latest 